In [0]:
import torch as t

In [4]:
print(t.__version__)

1.4.0


In [5]:
x = t.Tensor([5, 3]) # Tensor is called an array basically.
y = t.Tensor([2, 1])

print(x*y)

tensor([10.,  3.])


In [8]:
zeros = t.zeros([2, 5]) #similarly with numpy.zeros
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
rand = t.rand([2, 5])
rand

tensor([[0.7393, 0.1394, 0.6042, 0.2833, 0.1204],
        [0.1525, 0.7550, 0.8247, 0.8038, 0.8301]])

In [13]:
# Reshaping process name view() in PyTorch.

rand.view([1, 10])

tensor([[0.7393, 0.1394, 0.6042, 0.2833, 0.1204, 0.1525, 0.7550, 0.8247, 0.8038,
         0.8301]])